# Feature tracker
feature num: 1000
track_err_thres: 10
track_win_size:
- 21
- 21
extract_win_size: 12

# Disparity estimator
disparity_range: 100
kernel_radius: 12
ncc_gaussian_std: 2
msd_gap: 10

# Time estimation mode
time_estimation: True

# Visualize
# show disparity inlier requires ground truth disparity
show_disparity_inlier: True
show_disparity: True
semi_dense: True

